Move admin/settings to ember
puzzle/cryptopus pull request #430
Opened 2021-06-01 08:41 UTC by miosidler

2021-06-15 05:15 UTC, psunix requested changes
wow, lot's of changes and it looks pretty nice already!
some things to do:
- when I add an value (ip or country), it is not saved. when re-visiting the page, all options are gone
- remove app/views/admin/settings
- make sure no js errors in browser console
- hide team navigation when showing settings (see users admin branch), add back button
- after adding an option in the settings field, the option drop down is still open. can't we close this after adding an IP or country option?
![image](https://user-images.githubusercontent.com/655627/121996771-7faad000-cda9-11eb-80f6-8e0e87cbf56b.png)

2021-06-15 05:15 UTC, psunix commented on spec/controllers/api/admin/settings_controller_spec.rb
> +    it 'is not possible for non-admin to update setting' do
insert blank line between it blocks

2021-06-15 05:15 UTC, psunix commented on spec/controllers/api/admin/settings_controller_spec.rb
> +  context 'validate setting' do
blank line ...

2021-06-15 05:15 UTC, psunix commented on frontend/app/components/admin/setting-multiselect-with-create.js
> +    this.settingRecord.value = selected.map((option) => {
![image](https://user-images.githubusercontent.com/655627/121996190-6f462580-cda8-11eb-8b95-81b32872e3ee.png)

2021-06-15 05:15 UTC, psunix commented on frontend/app/components/admin/setting-multiselect-with-create.js
> +    this.settingRecord.value = selected.map((option) => {
always check browser console for errors

2021-06-16 14:57 UTC, psunix approved these changes
@TheWalkingLeek I added a check for making sure, geoip db is installed. could you do a review on that too?
please check the question about the locale
otherwise ... looks great !  :dancers:

2021-06-16 14:57 UTC, psunix commented on app/controllers/authentication/source_ip_checker.rb
> +    @whitelisted_country_codes ||= Setting.value('', :country_source_whitelist)
shouldn't we adjust the value method? getting rid of the prefix?

2021-06-16 14:59 UTC, psunix commented on frontend/app/components/admin/setting-multiselect-with-create.js
> +    this.settingRecord.value = selected.map((option) => {
those errors popped up because the settings were not available in db! had to reseed

2021-06-17 05:49 UTC, TheWalkingLeek commented on frontend/translations/en.yml
> +        whitelisted_countries: Whitelisted Countries
yup... currently we're still translating flash messages in the backend

2021-06-17 06:17 UTC, merged