Feature 428 admin users table styling improvements
puzzle/cryptopus pull request #438
Opened 2021-06-09 14:18 UTC by LianVin

2021-06-10 09:41 UTC, TheWalkingLeek requested changes
Already looks waaay better. Good work!
Still got some inputs :)

2021-06-10 09:41 UTC, TheWalkingLeek commented on frontend/app/templates/components/admin/user/table-row.hbs
> +  <td>{{@user.auth}}{{#if @user.providerUid}}:{{/if}} {{@user.providerUid}}</td>
Looks kinda strange without the line breaks around the `#if` no?

2021-06-10 09:41 UTC, TheWalkingLeek commented on frontend/tests/integration/helpers/format-role-test.js
> +module('Integration | Helper | format-role', function(hooks) {
What? Why is this here? There isn't even a format-role helper

2021-06-10 09:41 UTC, TheWalkingLeek commented on frontend/app/templates/components/admin/user/table.hbs
> +        </span>
This looks somewhat worse like this no? The tooltip is not correct and maybe you could give it a margin from the right.
Right now it just looks a bit randomly placed without real context (at least to me)

2021-06-10 09:41 UTC, TheWalkingLeek commented on frontend/app/templates/admin/users.hbs
> +    </LinkTo>
Maybe style the back-button like on the account-show page. https://github.com/puzzle/cryptopus/blob/5e89e8b0fd472a01764d980a1825f1ee296a4027/frontend/app/templates/components/account/show.hbs#L10

2021-06-14 14:55 UTC, luca-bruegger commented
So far finished, but there are still the one and other things missing:
- [ ] Test the admin/users component within admin/users-test.js
- [ ] Fix admin/table test. Entailed in admin/user/table-test.js

2021-06-18 12:15 UTC, merged