Bug fix system specs refs #436
puzzle/cryptopus pull request #445
Opened 2021-06-15 12:48 UTC by miosidler

2021-06-18 11:37 UTC, luca-bruegger requested changes
Some small things to fix - nice that those tests are up & running again 🚀

2021-06-18 11:37 UTC, luca-bruegger commented on spec/system/ajax_hook_system_spec.rb
> +  it 'show user has role user' do
'shows user has default user role'

2021-06-18 11:37 UTC, luca-bruegger commented on spec/system/teammember_system_spec.rb
> -    #   require 'pry'; binding.pry;
Are those commented lines needed? Maybe delete them? 😉

2021-06-18 11:37 UTC, luca-bruegger commented on spec/system/teams_page_system_spec.rb
> +
Blank line

2021-06-18 13:17 UTC, luca-bruegger approved these changes
Looks fine for me now! 🚀

2021-06-21 06:03 UTC, TheWalkingLeek approved these changes
Looking good! 👍🏼

2021-06-21 06:23 UTC, TheWalkingLeek requested changes
Yikes, seems to have broken again after rebasing :/

2021-06-21 06:56 UTC, merged