Add system spec, adjust build for testing
puzzle/cryptopus pull request #481
Opened 2021-06-30 11:26 UTC by miosidler

2021-07-02 09:23 UTC, TheWalkingLeek requested changes
Already looks pretty good, just a few nitpicks

2021-07-02 09:23 UTC, TheWalkingLeek commented on spec/system/create_user_system_spec.rb
> +      # expect(page).to have_text(user_attrs[:username])
can you not just remove this line? Spec works locally aswell on my machine

2021-07-06 16:41 UTC, carlobeltrame approved these changes
Sieht gut aus! Habs jetzt nicht selber laufen lassen, laufen die system specs so bei dir durch? Wie ich verstanden habe laufen die ja nur im nightly CI

2021-07-06 16:41 UTC, carlobeltrame commented on spec/system/account_modal_system_spec.rb
> +    expect(page).to have_css('.dropdown-toggle', text: 'Add')
Brauchts hier wirklich immer ein expect und ein find für das gleiche? Ist die failure message viel unverständlicher wenn erst ein find failt?

2021-07-06 16:41 UTC, carlobeltrame commented on spec/system/create_user_system_spec.rb
> -      expect(page).to have_text(user_attrs[:username])
Was hat sich hier geändert dass das nicht mehr angezeigt wird?

2021-07-06 16:41 UTC, carlobeltrame commented on spec/system/update_password_modal_system_spec.rb
> +#  Copyright (c) 2008-2017, Puzzle ITC GmbH. This file is part of
Allenfalls auf 2021 anpassen?

2021-07-09 09:44 UTC, miosidler commented on spec/system/create_user_system_spec.rb
> -      expect(page).to have_text(user_attrs[:username])
Hat noch ein page refresh gefehlt, habe das expect nun wieder eingefügt und der spec läuft durch. (System specs laufen ab dieser PR auf jeder PR durch)

2021-07-15 11:37 UTC, carlobeltrame approved these changes

2021-07-15 13:35 UTC, closed without merging