Add Encryptable::File
puzzle/cryptopus pull request #547
Opened 2022-02-17 15:15 UTC by luca-bruegger

2022-02-21 15:31 UTC, mtnstar requested changes

2022-05-12 08:46 UTC, mtnstar requested changes
thanks for the great effort ! huge PR ! lot's of code ... almost there ...

* check file content type column
* find an elegant solution for determine sti file type in controller by json

2022-05-12 08:46 UTC, mtnstar commented on app/serializers/folder_minimal_serializer.rb
> +    object.encryptables.reject do |encryptable|
now I know what you meant ... looks like a ok solution.
problem is that all encryptable files are fetched from db this way.
but the idea is to move files anyway to same layer as credentials, ose secrets are.
so we leave it that way for now.

2022-05-12 08:46 UTC, mtnstar commented on app/serializers/folder_minimal_serializer.rb
> +    object.encryptables.reject do |encryptable|
now I know what you meant ... looks like a ok solution.
problem is that all encryptable files are fetched from db this way.
but the idea is to move files anyway to same layer as credentials, ose secrets are.
so we leave it that way for now.

2022-05-12 08:46 UTC, mtnstar commented on config/locales/en.yml
> +        encryptable/file:
:+1:

2022-05-12 08:46 UTC, mtnstar commented on config/locales/en.yml
> +        encryptable/file:
:+1:

2022-05-12 08:46 UTC, mtnstar commented on db/migrate/20220214135340_move_files_from_credential_to_folder.rb
> +class MoveFilesFromCredentialToFolder < ActiveRecord::Migration[6.1]
right class name?
we're not yet moving file entries to folder, are we?

2022-05-12 08:46 UTC, mtnstar commented on db/migrate/20220214135340_move_files_from_credential_to_folder.rb
> +class MoveFilesFromCredentialToFolder < ActiveRecord::Migration[6.1]
right class name?
we're not yet moving file entries to folder, are we?

2022-05-12 08:46 UTC, mtnstar commented on db/migrate/20220214135340_move_files_from_credential_to_folder.rb
> +  end
well done migration :smile:

2022-05-12 08:46 UTC, mtnstar commented on db/migrate/20220214135340_move_files_from_credential_to_folder.rb
> +  end
well done migration :smile:

2022-05-12 08:46 UTC, mtnstar commented on db/migrate/20220214135340_move_files_from_credential_to_folder.rb
> +    add_column :encryptables, :content_type, :text
content type is available as a attr ... so no need to encrypt it ?!

2022-05-12 08:46 UTC, mtnstar commented on db/migrate/20220214135340_move_files_from_credential_to_folder.rb
> +    add_column :encryptables, :content_type, :text
content type is available as a attr ... so no need to encrypt it ?!

2022-05-12 08:46 UTC, mtnstar commented on frontend/app/models/encryptable-file.js
> +    const credential_id = await this.encryptableCredential.get("id");
javascript uses camel case, not snake case for variables and methods
```suggestion
    const credentialId = await this.encryptableCredential.get("id");
```

2022-05-12 08:46 UTC, mtnstar commented on frontend/app/models/encryptable-file.js
> +    const credential_id = await this.encryptableCredential.get("id");
javascript uses camel case, not snake case for variables and methods
```suggestion
    const credentialId = await this.encryptableCredential.get("id");
```

2022-05-12 08:46 UTC, mtnstar commented on spec/controllers/api/encryptables_controller_spec.rb
> +      file_params = {
is this variable required? id: file.id looks pretty short ...

2022-05-12 08:46 UTC, mtnstar commented on spec/controllers/api/encryptables_controller_spec.rb
> +      file_params = {
is this variable required? id: file.id looks pretty short ...

2022-05-12 08:46 UTC, mtnstar commented on spec/controllers/api/encryptables_controller_spec.rb
> +    it 'creates new encryptable file if part of the team' do
```suggestion
    it 'creates new encryptable file' do
```

2022-05-12 08:46 UTC, mtnstar commented on spec/controllers/api/encryptables_controller_spec.rb
> +    it 'creates new encryptable file if part of the team' do
```suggestion
    it 'creates new encryptable file' do
```

2022-05-12 08:46 UTC, mtnstar commented on spec/system/encryptable_files_modal_system_spec.rb
> +  # TODO: adjust tests after implementing/fixing encryptable files modal
TODO ? do we have to fix this?

2022-05-12 08:46 UTC, mtnstar commented on spec/system/encryptable_files_modal_system_spec.rb
> +  # TODO: adjust tests after implementing/fixing encryptable files modal
TODO ? do we have to fix this?

2022-05-12 12:21 UTC, luca-bruegger commented on app/controllers/api/encryptables_controller.rb
>    self.permitted_attrs = [:name, :description, :folder_id, :tag]
This already happens within the `permitted_attrs` method.

2022-05-16 05:55 UTC, luca-bruegger commented on app/controllers/api/encryptables_controller.rb
>        encryptable.class
This is going to be resolved on the follow-up branch: https://github.com/puzzle/cryptopus/tree/feature/530-encryptable-file-controller-cleanup

2022-05-16 06:49 UTC, mtnstar approved these changes
:partying_face:

2022-05-16 06:49 UTC, mtnstar commented on app/controllers/api/encryptables_controller.rb
> +  def create(options = {})
remove this options ... use before_save from dry crud as discussed

2022-05-16 07:05 UTC, merged