Feature/541 provide sorting in admin/users view
puzzle/cryptopus pull request #575
Opened 2022-03-18 07:37 UTC by RamonaChristen

admin/user table can now be sorted by each attribute by clicking on the small arrow next to it in the table header. Attributes are initially sorted in ascending order, a second click sorts in descending order - except for the "last login at" attribute which is initially sorted in descending order to display most recent logins at the top.

2022-03-18 11:09 UTC, luca-bruegger requested changes
Wow, congrats! You've implemented an astonishing algorithm to sort values :rocket: 

I left some notes directly within the code. You're on the right path.

Finally, let @Robin481 take a last look, to make sure everything is ok.

2022-03-18 11:09 UTC, luca-bruegger commented on frontend/app/components/admin/user/table.js
> +            if (userA.username > userB.username) return 1 * asc;
```suggestion
            return (userA.username < userB.username ? -1 : 1) * asc;
```

2022-03-18 11:09 UTC, luca-bruegger commented on frontend/app/components/admin/user/table.js
> +            return 0;
Use ternary if possible

2022-03-18 11:09 UTC, luca-bruegger commented on frontend/app/components/admin/user/table.js
> +            }
Create a new method for each case additionally. As it increases readability.

2022-03-20 18:11 UTC, RamonaChristen commented
Thank you for your feedback! We tried to implement all your suggested changes and everything seems to be working out well. 
@Robin481 do you have anything to add to this?

2022-03-21 08:07 UTC, Robin481 commented
Hi @RamonaChristen 
This looks really good to me.

2 small notes:
- I don't think the name sorting should consider upper-/lowercase. Examples: Currently the usernames `abc, bcd and cde` will all appear before `Abc, Bcd and Cde`)
This can be solved very easily for example like this:
```          
          case "username":
            return this.sortAttributes(userA.username.toLowerCase(), userB.username.toLowerCase(), asc);
          case "givenname":
            return this.sortAttributes(userA.givenname.toLowerCase(), userB.givenname.toLowerCase(), asc);
```
- Currently the Name sorting (2nd row in the table) doesn't consider a Person's surname so for example several people with the same givenname won't necessarily be sorted correctly when looking at their surname. This should also be easily solved by just giving the sorting "algorithm" the person's fullname instead of only the givenname.

Besides that I really like what you did here, good job!
Implement the little changes from above, make sure the branch is rebased to the current state of the main branch and then there is nothing in the way of a fun little merge :partying_face: :balloon:

2022-03-21 11:17 UTC, Robin481 approved these changes
Nice! :tada:

2022-03-21 11:18 UTC, merged