Improvment/translation encryptable credentials
puzzle/cryptopus pull request #602
Opened 2022-04-07 11:43 UTC by lkleisa

2022-04-07 17:26 UTC, mtnstar requested changes
please take some more time to clean the locale files up.

check what's still required in backend translations. we can probably remove quite a lot.
check in controllers where translation (method t) is still used. 

please concern STI encryptable names. so encryptable::credentials, encryptable::ose_secret, ...
make sure this is used everywhere in locale files. so there is no place where only encryptable is used. 

last but not least, make sure all tests are running :green_circle:

2022-04-07 17:26 UTC, mtnstar commented on frontend/translations/ch_be.yml
> +      encryptable: Zuägangsdate
concern sti name here.
encryptable.credentials

2022-04-07 17:26 UTC, mtnstar commented on frontend/translations/ch_be.yml
> +        encryptable: Zuägangsdate
does it make sense to have encryptable.encryptable ?

2022-04-07 17:26 UTC, mtnstar commented on frontend/translations/en.yml
> +    delete_account: Delete the Credentials
rename ... the term account should not be present anymore

2022-04-07 17:32 UTC, mtnstar commented
familiarize your-self with Rails i18n https://guides.rubyonrails.org/i18n.html
and emberjs https://github.com/ember-intl/ember-intl

2022-05-02 05:51 UTC, mtnstar requested changes
is this PR complete?
I'm a bit confused ... shouldn't there be also changes in frontend locale files?

2022-05-02 05:51 UTC, mtnstar commented on config/docker/postgresql/docker-compose.yml
> +version: "2"
this file does not belong in this PR, does it ?

2022-05-02 05:51 UTC, mtnstar commented on config/docker/postgresql/postgres-prod.env
> +RAILS_DB_USERNAME=root
same ...

2022-05-02 05:51 UTC, mtnstar commented on config/i18n-tasks-yml
> +# i18n-tasks works on itself! this is the internal config
? what is this file for?
strange extension ... -yml ?

2022-05-02 05:51 UTC, mtnstar commented on config/i18n-tasks.yml
> +# i18n-tasks finds and manages missing and unused translations: https://github.com/glebm/i18n-tasks
same file as above ... do we need it?

2022-05-02 05:51 UTC, mtnstar commented on config/locales/ru.yml
>    maintenance_tasks: "Задачи обслуживания"
ru still required? all other files removed?

2022-05-02 06:10 UTC, lkleisa commented on frontend/translations/ch_be.yml
> +      encryptable: Zuägangsdate
https://github.com/puzzle/cryptopus/issues/605

2022-05-02 07:12 UTC, mtnstar commented on config/locales/en.yml
> +      uploaded: Die Datei wurde erfolgreich hochgeladen.
german ?

2022-05-02 07:14 UTC, mtnstar commented
going to fix this in new issue #605

2022-05-02 07:14 UTC, closed without merging