Feature/593 recrypt
puzzle/cryptopus pull request #625
Opened 2022-05-24 13:19 UTC by luca-bruegger

2022-05-30 07:19 UTC, mtnstar requested changes
so far so good :rocket: 

still some things to check:

- make sure you handle cases where previous recrypt has failed or recrypt is in progress
- extend specs to make sure every thing is tested .. including team password reset during recrypt, ...
- just keep it simple and use hash map for a list of available encryption algorithms

2022-05-30 07:19 UTC, mtnstar commented on app/utils/crypto/symmetric/recrypt.rb
> +    perform
call perform from the outside, not inside constructor ...
BlaClass.new(args).perform

2022-05-30 07:19 UTC, mtnstar commented on app/utils/crypto/symmetric/recrypt.rb
> +    return if Crypto::EncryptionAlgorithm.latest_in_use?(@team)
don't we also have to check if recrypt is in progress or failed?

2022-05-30 07:19 UTC, mtnstar commented on app/utils/crypto/symmetric/recrypt.rb
> +  def entailed_encryptables
```suggestion
  def team_encryptables
```
?

2022-05-30 07:19 UTC, mtnstar commented on db/migrate/20220517131300_change_tables_to_support_recrypt.rb
> +    add_column :teams, :encryption_algorithm, :string, default: 'AES256', null: false
is it wise to use this deprecated value as default?
maybe first add new column ... update all existing entries .. then make column not null

2022-05-30 07:19 UTC, mtnstar commented on app/utils/crypto/symmetric/recrypt.rb
> +    @team.folders.map(&:encryptables).flatten
do not use map here.
use arel/sql to get all encryptables belonging to a team.
consider moving this getter to team model class
don't forget to include encryptable files which do not have a folder id assigned.

2022-05-30 07:19 UTC, mtnstar commented on spec/unit/utils/crypto/symmetric/recrypt_spec.rb
> +    expect(team.recrypt_state).to eq 'done'
also test resetting of team password?

2022-05-30 07:19 UTC, mtnstar commented on spec/unit/utils/crypto/symmetric/recrypt_spec.rb
> +    described_class.new(alice, team, private_key)
it's not obvious that new also performs the recrypt.
so as explained further up ... make sure you call perform explicit

2022-05-30 07:19 UTC, mtnstar commented on spec/unit/utils/crypto/symmetric/recrypt_spec.rb
> +    require 'pry'; binding.pry
pry ...

2022-05-30 07:19 UTC, mtnstar commented on spec/unit/utils/crypto/symmetric/recrypt_spec.rb
> +    defect_encryptable.save
invalid or broken instead of defect? defective ?

2022-05-31 05:46 UTC, mtnstar requested changes
some more feedback ... keep going :wink:

2022-05-31 05:46 UTC, mtnstar commented on app/utils/crypto/encryption_algorithm.rb
> +class Crypto::EncryptionAlgorithm
can't we just add this to Crypto::Symmetric ?
does it make sense to have it's own class here?

2022-05-31 05:46 UTC, mtnstar commented on app/models/team.rb
> +    Crypto::EncryptionAlgorithm.get_class(self.encryption_algorithm).password_bytesize
```suggestion
    Crypto::EncryptionAlgorithm::ALGORITHMS[self.encryption_algorithm].password_bytesize ?
```

2022-05-31 05:46 UTC, mtnstar commented on app/models/team.rb
> +  def encryptables
for getting a list of all encryptables ?

2022-05-31 05:46 UTC, mtnstar commented on app/utils/crypto/symmetric/aes256.rb
> +    password_bytesize = 32
maybe use class_attribute in base class ?

2022-05-31 05:46 UTC, mtnstar commented on app/utils/crypto/symmetric/recrypt.rb
> +    return if latest_in_use? || recrypt_not_ready?
maybe find a better name?
latest? what does latest mean here?
**already_recrypted?**

or .... requires_recrypt? and invert with unless

2022-06-03 08:01 UTC, mtnstar commented on spec/unit/utils/crypto/symmetric/recrypt_spec.rb
> +  def mocked_team
create_broken_encryptable ?
why returning team fixture here?
maybe just create borken encryptable ... it's included in team1 encryptables then

2022-06-03 09:11 UTC, luca-bruegger commented on app/models/team.rb
> +    Crypto::Symmetric::EncryptionAlgorithm::ALGORITHMS[encryption_algorithm].password_bitsize
I assume that bitsize is better than bytesize. As 256 stands for bits and not bytes.

2022-06-09 18:42 UTC, mtnstar requested changes
thanks again for the great effort getting this done ! good work.

check the comments ... some important inputs and maybe things we should discuss ... anyway ... looks like reaching the :checkered_flag: soon :wink:

2022-06-09 18:42 UTC, mtnstar commented on app/models/team.rb
>    validates :description, length: { maximum: 300 }
add something like:

`validates :encryption_algorithm, inclusion: Crypto::Symmetric::ALGORITHMS.keys`

2022-06-09 18:42 UTC, mtnstar commented on app/models/team.rb
> +  def encryption_algorithm=(algorithm)
use validation inclusion instead of overriding setter

2022-06-09 18:42 UTC, mtnstar commented on app/models/team.rb
> +    Crypto::Symmetric::ALGORITHMS[encryption_algorithm].password_bitsize
create encryption_class getter method and use it also here

2022-06-09 18:42 UTC, mtnstar commented on app/models/team.rb
> +  def update_encryption_algorithm
set this from outside in recrypt domain class
team model should not care about this

2022-06-09 18:42 UTC, mtnstar commented on app/utils/crypto/symmetric.rb
> +    def latest_algorithm
maybe add as class constant at top?

`LATEST_ALGORITHM = 'AES256'`

2022-06-09 18:42 UTC, mtnstar commented on app/utils/crypto/symmetric.rb
> +    def all
naming? symmetric.all?

2022-06-09 18:42 UTC, mtnstar commented on app/utils/crypto/symmetric/recrypt.rb
> +
first set new algorithm on team

2022-06-09 18:42 UTC, mtnstar commented on db/migrate/20220517131300_change_tables_to_support_recrypt.rb
> +    Team.update_all(encryption_algorithm: "AES256")
```suggestion
    Team.update_all(encryption_algorithm: 'AES256')
```

2022-06-09 18:42 UTC, mtnstar commented on db/migrate/20220517131300_change_tables_to_support_recrypt.rb
> +    add_column :teams, :recrypt_state, :integer, default: 1, null: false
do not use magic number 1 here ...
read it from team recrypt state

2022-06-09 18:42 UTC, mtnstar commented on db/migrate/20220609063817_rename_password_to_encrypted_team_password.rb
> +    rename_column :teammembers, :password, :encrypted_team_password
:heart_eyes:

2022-06-09 18:42 UTC, mtnstar commented on spec/unit/utils/crypto/symmetric/recrypt_spec.rb
> +    broken_encryptable = team.folders.first.encryptables.first
```suggestion
    broken_encryptable = team.encryptables.first
```

2022-06-09 18:42 UTC, mtnstar commented on spec/unit/utils/crypto/symmetric/recrypt_spec.rb
> +
make also sure Encryptable::Files are also recrypted !

2022-06-09 18:42 UTC, mtnstar commented on app/models/team.rb
> +    Encryptable.joins("LEFT JOIN folders ON encryptables.folder_id = folders.id
do not forget to include encryptable files !

2022-06-13 09:17 UTC, mtnstar requested changes

2022-06-13 09:17 UTC, mtnstar commented on app/models/encryptable.rb
> +  def recrypt(team_password, new_team_password)
maybe add param current_encryption_algorithm ?

2022-06-20 13:15 UTC, luca-bruegger reviewed
Some little inputs

2022-06-20 13:15 UTC, luca-bruegger commented on app/models/team/shared.rb
> +    end
Move into self needed?

2022-06-20 13:15 UTC, luca-bruegger commented on db/migrate/20220517131300_change_tables_to_support_recrypt.rb
> +  end
Maybe remove method and directly call `update_all`?

2022-06-20 13:15 UTC, luca-bruegger commented on spec/migrations/use_encrypted_data_for_account_credentials_spec.rb.disabled
> +    encrypted_values = { data: data, iv: iv }
Create additional method to retrieve `encrypted_values` to increase readability and to keep it DRY?

2022-06-21 05:52 UTC, luca-bruegger commented on spec/migrations/use_encrypted_data_for_account_credentials_spec.rb.disabled
> +    encrypted_values = { data: data, iv: iv }
Ignored as migration is disabled

2022-06-23 11:00 UTC, mtnstar commented on app/models/team.rb
> +  def password_bytesize
byte vs. bit ?

2022-06-23 11:07 UTC, mtnstar commented on spec/unit/utils/crypto/symmetric/recrypt_spec.rb
> +
also here .. add check that encryptable can still be decrypted as before

2022-06-23 11:08 UTC, mtnstar approved these changes
looks almost perfect now !!! :rocket: :partying_face: 

just check the comments ... small improvements ...
we wanna make sure nothing goes wrong with this important feature

2023-07-17 13:20 UTC, mtnstar commented
going to be merged with #728

2023-07-17 13:20 UTC, closed without merging